#!/bin/zsh

make_tree() {
	local fileName='directory_tree.md'

	# --- Parse args -----------------------------------------------------------
	local -a include_overrides=()
	while [[ $# -gt 0 ]]; do
		case $1 in
			--include|-i)
				shift
				[[ -n "${1:-}" ]] && include_overrides+=(${(s:,:)1})
				;;
			--help|-h)
				echo "Usage: make_tree.sh [--include name1,name2,...]"
				echo "  Writes a fenced directory_tree.md at the git repo root."
				echo "  --include re-adds names the exclusion set would otherwise hide."
				return 0
				;;
			*)
				echo "Unknown option: $1" >&2
				return 1
				;;
		esac
		shift
	done

	# --- Anchor at the repo root ---------------------------------------------
	# Run from a subdirectory and the tree still lands at the project root, not
	# wherever the skill happened to be invoked. Falls back to the current dir
	# when this isn't a git repo.
	local root
	root=$(git rev-parse --show-toplevel 2>/dev/null)
	if [[ -n "$root" ]]; then
		cd "$root" || { echo "cannot cd to repo root: $root" >&2; return 1; }
	fi
	local gitignore_file='.gitignore'

	# --- Build the exclusion set: core + derived from .gitignore --------------
	# NOTE: `tree -I` matches BASENAMES, not paths, and supports fnmatch globs.
	# So every pattern is reduced to its final path segment, and a .gitignore
	# entry like `docs/build/` excludes anything named `build` anywhere in the
	# tree — an intentional over-match, the closest `tree -I` can get.
	local -a exclude_list=(
		.git .DS_Store "$fileName"
		node_modules dist build .next out target coverage
		__pycache__ .pytest_cache .ruff_cache .mypy_cache
		venv .venv env
		'*.egg-info' settings.local.json
	)
	if [[ -f "$gitignore_file" ]]; then
		local line
		while IFS= read -r line || [[ -n "$line" ]]; do
			line=${line%%#*}                 # drop comments (inline or whole-line)
			line=${line//[[:space:]]/}       # strip whitespace (patterns carry none)
			[[ -z "$line" ]] && continue
			[[ "$line" == '!'* ]] && continue   # negations: unsupported by `tree -I`
			line=${line%/}                   # trailing slash = directory marker
			line=${line#/}                   # leading slash = root anchor (tree can't anchor)
			# strip trailing /* or /** wildcard segments BEFORE basename reduction — else
			# `build/**` or `**/.terraform/*` would collapse to a bare `*`/`**` that matches
			# every basename and excludes the entire tree.
			while [[ "$line" == */'*' || "$line" == */'**' ]]; do line=${line%/*}; done
			line=${line##*/}                 # basename only — `tree -I` matches names
			[[ -z "$line" ]] && continue
			[[ "$line" == '*' || "$line" == '**' ]] && continue   # never emit a match-everything pattern
			exclude_list+="$line"            # globs (*.log, *.pyc) pass straight through
		done < "$gitignore_file"
	fi

	# --- Dedupe, then honor --include overrides -------------------------------
	local -a unique_excludes=(${(u)exclude_list})
	local inc
	for inc in ${include_overrides[@]}; do
		unique_excludes=(${unique_excludes:#$inc})
	done
	local excludeDirs="${(j:|:)unique_excludes}"
	local -a tree_ignore_args=()
	[[ -n "$excludeDirs" ]] && tree_ignore_args=(-I "$excludeDirs")

	# --- Generate the tree ----------------------------------------------------
	if ! tree -a -L 10 ${tree_ignore_args[@]} --dirsfirst -sD --timefmt "%Y-%m-%d" -o "$fileName"; then
		echo "tree failed (is it installed? try 'brew install tree')" >&2
		return 1
	fi

	# --- Wrap in a fenced code block (mktemp: no stray 'temp' left behind) -----
	local tmp
	tmp=$(mktemp "${TMPDIR:-/tmp}/make_tree.XXXXXX") || { echo "mktemp failed" >&2; return 1; }
	if { echo '```bash'; cat "$fileName"; echo '```'; } > "$tmp" && mv "$tmp" "$fileName"; then
		:
	else
		rm -f "$tmp"
		echo "failed to wrap tree output" >&2
		return 1
	fi

	# --- Ensure directory_tree.md is gitignored -------------------------------
	# It's generated output and can be large; keep it out of version control.
	# Skip the per-repo entry when it's ALREADY ignored by any mechanism — a
	# global core.excludesfile, .git/info/exclude, or an existing .gitignore
	# line — so a globally-ignored setup never accrues redundant per-repo lines.
	# (`git check-ignore` fails outside a git repo, so the CWD-fallback path
	# still creates a local .gitignore.)
	if ! git check-ignore -q "$fileName" 2>/dev/null; then
		# add a separating newline only if the file exists and lacks a trailing one
		if [[ -s "$gitignore_file" && -n "$(tail -c1 "$gitignore_file")" ]]; then
			echo >> "$gitignore_file"
		fi
		{ echo "# generated by the directory-tree plugin"; echo "$fileName"; } >> "$gitignore_file"
	fi

	echo "Directory tree created as $PWD/$fileName"
}

make_tree "$@"
